### ISSUE TITLE
Missing PR's and branches after repo cleaning

### ISSUE THREAD

**Issue by nulinspiratie** [nulinspiratie/SilQ#196]
- [x] #160 Feature/analysis acquisitionparameter upgrade
- [x] #184 Make the path OS independent for get_pulse_sequence. @maij 
- [x] #182 Add a check if phase_reference is an attr of the class.@maij 
- [x] #176 adaptive threshold for nuclear readout @RostyslavSavytskyy 
- [x] #175 added analysis for nuclear state probability and electron readout
- [x] #176 Add plot_nuclear_up_proportions to SilQ
- [ ] #156 Fix/frequency modulation source initialization Keysight E8267D @RostyslavSavytskyy 
  Is this still relevant? Looking at the source code I do in fact see that the modulation source is set
- [x] #135 Add tools related to finding Coulomb peaks 
  Not sure if this can be recovered
- [x] #133 Add trace tools to SilQ

**Comment by maij** [comment]
Closed as everything appears resolved.
